apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  namespace: logging
spec:
  ports:
  - port: 9114
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: elasticsearch-exporter
