apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring-prometheus.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring-prometheus.labels" . | nindent 4 }}
