apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secrets-sync
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: db-user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-password