apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appName }}
    
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            - condition:
                equals: 
                  kubernetes.namespace: {{ .Values.appNamespace }}
              config:
                - type: container
                  paths:
                    - /var/log/pods/{{ .Values.appNamespace }}_${data.kubernetes.pod.name}_${data.kubernetes.pod.uid}/${data.kubernetes.container.name}/*.log

    processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}

    setup.dashboards.enabled: {{ .Values.setupDashboards }}
{{- if .Values.setupDashboards }}
    setup.kibana:
      host: {{ .Values.kibanaService }}
{{- end }}
    output.elasticsearch:
      hosts: [{{ .Values.esService}}]
