{{- if .Values.grafana.useExternalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "monitoring-grafana.fullname" . }}-admin-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: {{ include "monitoring-grafana.fullname" . }}-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
{{- end }}