apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring-grafana.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring-grafana.labels" . | nindent 4 }}
