apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-crud-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gitafolabi/aks-app.git
    targetRevision: main
    path: helm/crud-app-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s