apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: default
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: "https://crud-kv.vault.azure.net"
      tenantId: "f09536f4-5988-40db-808d-eabbdfbb5e63"
      authSecretRef:
        clientId:
          name: azure-sp-credentials
          key: client-id
        clientSecret:
          name: azure-sp-credentials
          key: client-secret